AllCops:
  TargetRubyVersion: 3.3

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Naming/FileName:
  Enabled: false

# Disable all Metrics cops
Metrics:
  Enabled: false
